-- RADAR_LOCAL_SEED_CONTRACT v1
-- Radar local/test seed entrypoint.
--
-- Supabase loads this file after migrations during `pnpm db:reset`.
-- This file orchestrates deterministic local/test seed fragments under
-- `supabase/seeds` after the relevant schema exists.
--
-- Current state:
-- - RAD-019 seeds deterministic local/test users, one workspace, memberships,
--   and representative audit activity for assertion/source/finding examples.
-- - Product tables for assertions, sources, runs, and findings are introduced
--   in later data-model tickets; do not create them here.
-- - Future customer-owned rows must be scoped by workspace_id or a
--   workspace-owned parent.
-- - Future local/demo seeds must stay deterministic and safe to recreate on
--   every local reset.
-- - production data must never be added here.
-- - Product runtime code must never import seed files or hardcoded product
--   result arrays.

\ir ./seeds/radar-demo-workspace.sql
