allowBuilds:
  '@sentry/cli': true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@sentry/cli'
  - protobufjs
  - sharp
  - unrs-resolver
overrides:
  lightningcss: npm:lightningcss-wasm@1.32.0
