insert into public.assertion_templates (
  id,
  workspace_id,
  name,
  description,
  category,
  priority,
  runner_type,
  purpose_template,
  expected_behavior_template,
  required_source_types,
  test_case_blueprints,
  is_system,
  metadata
)
values
  (
    '54000000-0000-4000-8000-000000000001',
    null,
    'Pricing & Plan Accuracy',
    'Verify pricing, plan limits, checkout promises, and AI/support answers against approved pricing sources.',
    'pricing',
    'high',
    'knowledge',
    'Verify that customer-facing pricing answers, plan limits, checkout guidance, and billing exception handling match the current approved pricing sources.',
    'Customer-facing answers must match the current pricing page or uploaded pricing policy, include correct plan limits, avoid invented discounts, and escalate billing exceptions to a human owner.',
    array['url', 'uploaded_document', 'manual_text']::public.source_type[],
    $$[{"title":"Customer asks which plan includes a key limit","type":"customer_question","input":{"scenario":"Ask about plan limits and upgrade requirements."},"expectedResult":"Answer matches the approved pricing source and does not invent plan details."}]$$::jsonb,
    true,
    '{"slug":"pricing-plan-accuracy","pack":"v1","source":"RAD-045"}'::jsonb
  ),
  (
    '54000000-0000-4000-8000-000000000002',
    null,
    'Refund & Cancellation',
    'Verify refund, cancellation, downgrade, and retention answers against the active customer policy.',
    'refund_cancellation',
    'high',
    'knowledge',
    'Verify that customer-facing refund, cancellation, downgrade, and retention answers match the active policy and route exceptions correctly.',
    'Answers must reflect the current refund and cancellation policy, state eligibility clearly, avoid unauthorized promises, and escalate ambiguous account-specific cases.',
    array['url', 'uploaded_document', 'manual_text']::public.source_type[],
    $$[{"title":"Customer asks whether they can cancel and receive a refund","type":"customer_question","input":{"scenario":"Ask about refund eligibility after cancellation."},"expectedResult":"Answer matches the approved refund policy and routes exceptions to a human owner."}]$$::jsonb,
    true,
    '{"slug":"refund-cancellation","pack":"v1","source":"RAD-045"}'::jsonb
  ),
  (
    '54000000-0000-4000-8000-000000000003',
    null,
    'Trial & Onboarding',
    'Verify signup, trial activation, welcome guidance, and first-run customer journeys.',
    'trial_onboarding',
    'medium',
    'journey',
    'Verify that trial users can complete the core signup and onboarding path and receive the expected first-run guidance.',
    'The trial journey should load, accept valid signup inputs, show the expected onboarding destination, and avoid broken or misleading customer-facing states.',
    array['url']::public.source_type[],
    $$[{"title":"New trial user reaches onboarding start","type":"journey_scenario","input":{"scenario":"Visit the signup entry point and verify the onboarding destination."},"expectedResult":"The journey reaches the expected onboarding state without a customer-facing blocker."}]$$::jsonb,
    true,
    '{"slug":"trial-onboarding","pack":"v1","source":"RAD-045"}'::jsonb
  ),
  (
    '54000000-0000-4000-8000-000000000004',
    null,
    'Billing & Invoices',
    'Verify invoice, receipt, failed-payment, and billing handoff promises.',
    'billing_invoices',
    'high',
    'integration',
    'Verify that customer-facing billing and invoice promises produce the expected handoff, receipt, or account state.',
    'Billing checks must return the expected status, create or expose the correct invoice/receipt handoff, and avoid silently dropping customer billing requests.',
    array['api_endpoint', 'support_bot_endpoint']::public.source_type[],
    $$[{"title":"Billing handoff returns expected state","type":"integration_check","input":{"scenario":"Call the configured billing or support handoff endpoint."},"expectedResult":"The endpoint returns the expected billing state or accepted handoff without leaking sensitive data."}]$$::jsonb,
    true,
    '{"slug":"billing-invoices","pack":"v1","source":"RAD-045"}'::jsonb
  ),
  (
    '54000000-0000-4000-8000-000000000005',
    null,
    'Support Escalation',
    'Verify account-risk, billing, and policy exceptions route to a human instead of dead-ending.',
    'support_escalation',
    'critical',
    'knowledge',
    'Verify that customer-facing support answers identify account-risk, billing, and policy exception cases and route them to a human owner.',
    'Support answers must avoid unsupported resolution promises, identify escalation-worthy cases, and provide the correct human handoff guidance.',
    array['manual_text', 'support_bot_endpoint', 'url']::public.source_type[],
    $$[{"title":"Customer raises an account-risk billing exception","type":"customer_question","input":{"scenario":"Ask for an exception that requires human review."},"expectedResult":"Answer acknowledges the issue and routes the customer to the approved human escalation path."}]$$::jsonb,
    true,
    '{"slug":"support-escalation","pack":"v1","source":"RAD-045"}'::jsonb
  )
on conflict (id) do update
set
  workspace_id = excluded.workspace_id,
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  priority = excluded.priority,
  runner_type = excluded.runner_type,
  purpose_template = excluded.purpose_template,
  expected_behavior_template = excluded.expected_behavior_template,
  required_source_types = excluded.required_source_types,
  test_case_blueprints = excluded.test_case_blueprints,
  is_system = excluded.is_system,
  metadata = excluded.metadata,
  updated_at = now();
